services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vpa_frontend
    depends_on:
      - backend
    ports:
      - "8080:80"
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "3"